AuthxCredential.validate - Multiple changes
* Fix crash for undefined reference to `AuthenticatorTarget`
    * This is a private class.
* Expect a credential instead of bare token
* Fix types on setter/getter
* Accept optional `$flow`. Make default visible.