Backdrop - Stop running CliRunnerTest on php80+drush
There seems to be a problem in using `drush ev` with our current versions of Drush / Backdrop / PHP 8.0

```
[bknix-edge:~/bknix/build/bcmaster/web/modules/civicrm] drush ev 'echo 123;'
PDOException: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens: SELECT name FROM {system} WHERE type=&#039;module&#039; AND status=1; Array
(
    [:type] => module
    [:status] => 1
)
 in drush_db_select() (line 131 of phar:///Users/totten/bknix/extern/drush8.phar/includes/dbtng.inc).
Drush command terminated abnormally due to an unrecoverable error.
```

The problem is not specific to the functionality `civicrm-core.git` -- it
affects anything going through `drush-backdrop` and seems to be blocked on
upstream fixes.  But it's been generating a bunch of red-dot noise for the
past few months, and there's no point in that.

Note that `CliRunnerTest` still provides coverage for several adjacent combinations, so I'm not
too concerned about substantive change affecting civicrm-core. Those adjacent combinations are:

* PHP80 + D7 + Drush (differ only by CMS)
* PHP80 + Backdrop + Cv (differ only by CLI-runner)
* PHP7x + Bacdkrop + Drush (differ only by PHP-version)