loadServices: tighten up file match regex
Before: Civi code living under a path containing the characters php
(such as ~/src/php/civicrm) will crash trying to load services with
a message like the following:
   ReflectionException: Class Civi\Api4\Service\Spec\Provider\src
   does not exist in ReflectionClass->__construct()

After: Civi loads services normally no matter what the enclosing path